# Generated by Django 5.0.6 on 2024-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdb',
            name='PRICE',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
