# Generated by Django 5.0.6 on 2024-06-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_roomdb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdb',
            name='IMAGE',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
