# Generated by Django 5.0.6 on 2024-07-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_roomdb_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roomdb',
            new_name='Accomdb',
        ),
    ]
