# Generated by Django 5.0.6 on 2024-07-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_roomdb_accomdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomdb',
            name='PRICE',
        ),
    ]
