# Generated by Django 5.0.6 on 2024-07-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_accomdb_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roomdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROOMNAME', models.CharField(blank=True, max_length=50, null=True)),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('PRICE', models.IntegerField(blank=True, null=True)),
                ('IMAGE', models.FileField(blank=True, null=True, upload_to='images')),
                ('SIZE', models.IntegerField(blank=True, null=True)),
                ('VIEW', models.CharField(blank=True, max_length=50, null=True)),
                ('DESCRIPTION', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
