# Generated by Django 5.0.6 on 2024-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_roomdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdb',
            name='BED',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roomdb',
            name='SIZE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
