# Generated by Django 5.0.6 on 2024-08-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_roomdb_bed_alter_roomdb_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdb',
            old_name='ROOMNAME',
            new_name='ROOMTYPE',
        ),
    ]
