# Generated by Django 5.0.6 on 2024-08-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_roomname_roomdb_roomtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdb',
            old_name='BED',
            new_name='AMENITIES',
        ),
        migrations.RenameField(
            model_name='roomdb',
            old_name='DESCRIPTION',
            new_name='BEDDING',
        ),
        migrations.RenameField(
            model_name='roomdb',
            old_name='SIZE',
            new_name='POOL',
        ),
        migrations.RenameField(
            model_name='roomdb',
            old_name='VIEW',
            new_name='VIEWS',
        ),
    ]
