# Generated by Django 5.0.6 on 2024-08-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_bed_roomdb_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Iteams', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='images')),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='roomdb',
            name='AMENITIES',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
