# Generated by Django 5.0.6 on 2024-08-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_foods_alter_roomdb_amenities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foods',
            new_name='fooddb',
        ),
    ]
