# Generated by Django 5.0.6 on 2024-08-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_foods_fooddb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddb',
            old_name='Description',
            new_name='DESCRIPTION',
        ),
        migrations.RenameField(
            model_name='fooddb',
            old_name='Image',
            new_name='IMAGE',
        ),
        migrations.RenameField(
            model_name='fooddb',
            old_name='Iteams',
            new_name='ITEAMS',
        ),
    ]
