# Generated by Django 5.0.6 on 2024-08-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_description_fooddb_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddb',
            name='DESCRIPTION',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fooddb',
            name='IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
