# Generated by Django 5.0.6 on 2024-08-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_fooddb_description_alter_fooddb_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fooddb',
        ),
    ]
