# Generated by Django 5.0.6 on 2024-08-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_delete_fooddb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooddb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FNAME', models.CharField(blank=True, max_length=50, null=True)),
                ('FIMAGE', models.FileField(blank=True, null=True, upload_to='images')),
                ('FDESCRIPTION', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
