# Generated by Django 5.0.6 on 2024-08-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_fooddb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooditeamsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FOODTYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('FONAME', models.CharField(blank=True, max_length=50, null=True)),
                ('FOPRICE', models.IntegerField(blank=True, null=True)),
                ('FOIMAGE', models.FileField(blank=True, null=True, upload_to='images')),
                ('FODESCRIPTION', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
