# Generated by Django 5.0.6 on 2024-08-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_fooditeamsdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditeamsdb',
            name='FOIMAGE',
        ),
    ]
