# Generated by Django 5.0.6 on 2024-08-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_fooditeamsdb_foimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditeamsdb',
            name='FOIMAGE',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
