# Generated by Django 5.0.6 on 2024-07-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('SUBJECT', models.CharField(blank=True, max_length=50, null=True)),
                ('MESSAGE', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
