# Generated by Django 5.0.6 on 2024-07-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condb',
            name='EMAIL',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
