# Generated by Django 5.0.6 on 2025-06-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0002_alter_condb_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rigesterdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Email', models.EmailField(blank=True, max_length=500, null=True)),
                ('Password', models.CharField(blank=True, max_length=500, null=True)),
                ('ConfirmPassword', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
