# Generated by Django 5.0.6 on 2025-06-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0003_rigesterdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rigesterdb',
            new_name='Registerdb',
        ),
    ]
