# Generated by Django 5.0.6 on 2025-06-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0004_rename_rigesterdb_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(blank=True, max_length=500, null=True)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('customers', models.PositiveIntegerField()),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
