# Generated by Django 5.0.6 on 2025-06-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0005_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='booked_on',
        ),
    ]
