# Generated by Django 5.0.6 on 2025-06-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0006_remove_rooms_booked_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Hostdb',
        ),
    ]
