# Generated by Django 5.0.6 on 2025-06-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0007_rename_rooms_hostdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostname', models.CharField(blank=True, max_length=500, null=True)),
                ('Mobnum', models.IntegerField(blank=True, max_length=10, null=True)),
                ('Proof', models.FileField(blank=True, null=True, upload_to='images')),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Requerments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
