# Generated by Django 5.0.6 on 2025-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0008_paymentdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdb',
            name='Mobnum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
