# Generated by Django 5.0.6 on 2025-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0009_alter_paymentdb_mobnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='paymail',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
    ]
