# Generated by Django 5.0.6 on 2025-06-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0010_paymentdb_paymail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdb',
            name='Mobnum',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
