# Generated by Django 5.0.6 on 2025-06-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0011_alter_paymentdb_mobnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdb',
            old_name='paymail',
            new_name='Paymail',
        ),
        migrations.AlterField(
            model_name='paymentdb',
            name='Mobnum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
