# Generated by Django 5.0.6 on 2025-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0014_paymentdb_mobnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='Address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='paymentdb',
            name='Paymail',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='paymentdb',
            name='Proof',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='paymentdb',
            name='Requerments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
