# Generated by Django 5.0.6 on 2025-06-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0015_paymentdb_address_paymentdb_paymail_paymentdb_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdb',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='paymentdb',
            name='Paymail',
        ),
        migrations.RemoveField(
            model_name='paymentdb',
            name='Proof',
        ),
        migrations.RemoveField(
            model_name='paymentdb',
            name='Requerments',
        ),
    ]
