# Generated by Django 5.0.6 on 2025-06-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0016_remove_paymentdb_address_remove_paymentdb_paymail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='Paymail',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
    ]
