# Generated by Django 5.0.6 on 2025-06-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0017_paymentdb_paymail'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='Proof',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
