# Generated by Django 5.0.6 on 2025-06-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0018_paymentdb_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='Address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
