# Generated by Django 5.0.6 on 2025-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0020_paymentdb_requerments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdb',
            name='Paymail',
            field=models.EmailField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
    ]
