# Generated by Django 5.0.6 on 2025-06-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0022_alter_paymentdb_paymail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdb',
            name='Mobnum',
            field=models.CharField(default='0000000000', max_length=100),
            preserve_default=False,
        ),
    ]
