# Generated by Django 5.0.6 on 2025-06-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0024_alter_paymentdb_mobnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdb',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='paymentdb',
            name='Mobnum',
        ),
        migrations.RemoveField(
            model_name='paymentdb',
            name='Paymail',
        ),
        migrations.RemoveField(
            model_name='paymentdb',
            name='Proof',
        ),
        migrations.RemoveField(
            model_name='paymentdb',
            name='Requerments',
        ),
    ]
