# Generated by Django 5.0.6 on 2025-06-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0025_remove_paymentdb_address_remove_paymentdb_mobnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='Mobnum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
