# Generated by Django 5.0.6 on 2025-06-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0026_paymentdb_mobnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='Paymail',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
    ]
