# Generated by Django 5.0.6 on 2025-06-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0030_paymentdb_requerments'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdb',
            name='total_price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
