# Generated by Django 5.0.6 on 2025-06-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0031_hostdb_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdb',
            name='Total_price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
