# Generated by Django 5.0.6 on 2025-06-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacleinn', '0032_paymentdb_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdb',
            old_name='Total_price',
            new_name='Originaltotal_price',
        ),
    ]
